baseURL: 'https://52funny.github.io'
title: 52funny Blog
theme: hugo-notepadium

languageCode: zh-cn
hasCJKLanguage: true
enableEmoji: true
enableRobotsTXT: true

defaultContentLanguage: zh-hans
summaryLength: 100
paginate: 8

params:
  author: 52funny
  showWordCounter: true
  showToc: true
  style: auto
  slogan: < Code /> 
 
  nav:
    showCategories: true
    showTags: true
    custom:
      - title: Friends
        url: /friends

      - title: About
        url: /about

markup:
  codeFences: true
  noClasses: false
  goldmark:
    renderer:
      unsafe: true

